service: psycopg2-lambda-layer

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

layers:
  psycopg2-py39:
    description: "psycopg2 python postgresql client library."
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.9
    allowedAccounts:
      - '*'
    retain: true
